# -*- coding: utf-8 -*-
"""annsql_extract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRtNO5HsyQnZQxvKp1nnwKImYYq1sskr
"""

# Install packages with compatible dependency versions
!pip install -q annsql scanpy duckdb pyarrow zarr==2.18.3 numcodecs==0.12.1

!pip install mygene

# Import packages
import scanpy as sc
from AnnSQL import AnnSQL
from pathlib import Path
import numpy as np
import pandas as pd
from scipy import sparse
import mygene as mg

from google.colab import drive

drive.mount("/content/drive")

# Define data path
h5ad_path = "/content/drive/MyDrive/Colab Notebooks/SpatialCell_Lakehouse/data/bronze/a0805e92-3d1f-4866-af5c-5b903c6d910b.h5ad"

# Read data
adata = sc.read_h5ad(h5ad_path)

# Sanitize metadata for DuckDB by converting to PyArrow backend
adata.obs = adata.obs.convert_dtypes(dtype_backend="pyarrow")
adata.var = adata.var.convert_dtypes(dtype_backend="pyarrow")

# Force index types to standard objects to avoid 'str' dtype errors in DuckDB
adata.obs_names = adata.obs_names.astype('object')
adata.var_names = adata.var_names.astype('object')

# Initialize AnnSQL natively
asql = AnnSQL(adata=adata)

# Verify
print("AnnSQL initialized successfully.")
preview = asql.query("SELECT * FROM obs LIMIT 5")
display(preview)

# Define path to silver data directory and create it if its not there
silver_path = Path("/content/drive/MyDrive/Colab Notebooks/SpatialCell_Lakehouse/data/silver")
silver_path.mkdir(parents=True, exist_ok=True)

# Parse cell or spot data
obs = adata.obs.reset_index().rename(columns={"index": "obs_id"})
obs.to_parquet(silver_path / "obs.parquet", index=False)

#Gene metadata
var = adata.var.reset_index().rename(columns={"index": "gene_id"})

#Save to Parquet
var.to_parquet(silver_path / "var.parquet", index=False)

#Spatial coordinates
if "spatial" in adata.obsm:
  spatial = pd.DataFrame(
      adata.obsm["spatial"],
      columns=["spatial_x", "spatial_y"]
  )
  spatial["obs_id"] = adata.obs_names

  # Save to parquet
  spatial.to_parquet(silver_path / "spatial_coordinates.parquet", index=False)

# Avoid cnverting enitre matrix, import marker-gene panel

# Define a few liver marker genes from the literature
# https://www.journal-of-hepatology.eu/article/S0168-8278(24)00003-5/fulltext
CELLTYPE_MARKER_GENES = {'B cell': ['CD79A',
            'CD79B',
            'IGHM',
            'IGHA1',
            'IGHA2',
            'IGHG1',
            'IGHG2',
            'IGHG3',
            'IGHG4',
            'IGHGP',
            'IGKC',
            'IGLC2',
            'IGLC3',
            'IGLL5'],
 'Cellcycle': ['BIRC5', 'CDC20', 'CDK1', 'CDK4', 'HMGB2', 'MKI67', 'TOP2A'],
 'Cholangiocyte': ['APOA1',
                   'APOA2',
                   'APOC1',
                   'APOC3',
                   'AGXT',
                   'AMBP',
                   'ANXA4',
                   'CLDN1',
                   'DEFB1',
                   'EEF1A1',
                   'EPCAM',
                   'FXYD2',
                   'GNB2L1',
                   'HP',
                   'MT2A',
                   'NEAT1',
                   'RPL3',
                   'KRT18',
                   'KRT19',
                   'KRT7',
                   'KRT8',
                   'LGALS2',
                   'MUC1',
                   'MUC3A',
                   'MUC5B',
                   'PIGR',
                   'SCGB3A1',
                   'SLPI',
                   'SPINK1',
                   'TFF3'],
 'Endothelial': ['CD34',
                 'PLVAP',
                 'PODXL',
                 'ACKR1',
                 'RSPO3',
                 'WNT2',
                 'CLEC1B',
                 'CLEC4G',
                 'CLEC4M',
                 'CRHBP',
                 'FCN2',
                 'FCN3',
                 'STAB1',
                 'STAB2',
                 'C7',
                 'DNASE1L3',
                 'ENG',
                 'GSN',
                 'INMT',
                 'LIFR',
                 'PECAM1',
                 'PLAC8',
                 'RAMP3',
                 'TIMP3',
                 'VWF',
                 'ADRIF',
                 'AQP1',
                 'CLEC14A',
                 'ID1',
                 'IGFBP7',
                 'MGP',
                 'S100A6',
                 'SPARCL1',
                 'TM4SF1'],
 'Hepatocyte': ['ADH1A',
                'ADH1B',
                'ADH1C',
                'ADH4',
                'CES1',
                'CYP2E1',
                'CYP3A4',
                'CYP3A5',
                'DCXR',
                'GSTA1',
                'OAT',
                'ASGR1',
                'SERPINA1',
                'AGT',
                'ALB',
                'ALDOB',
                'APOA1',
                'CYP1A2',
                'CYP2A6',
                'CYP2A7',
                'CYP2D6',
                'FGA',
                'FGB',
                'GLS2',
                'HAL',
                'HAMP',
                'SDS'],
 'Lymphocyte': ['CD3D',
                'CD3E',
                'TRAC',
                'TRBC2',
                'CD4',
                'CD40LG',
                'IL7R',
                'LTB',
                'RCAN3',
                'S100A4',
                'SPOCK2',
                'CD8A',
                'CD8B',
                'FCGR3A',
                'GNLY',
                'GZMB',
                'TBX21',
                'XCL2',
                'CD7',
                'CTSW',
                'GATA3',
                'TRDC',
                'TRGC1',
                'TRGC2',
                'CD69',
                'CMC1',
                'EOMES',
                'GZMK',
                'KLRC1',
                'KLRF1',
                'XCL1'],
 'Macrophage/Myeloid': ['AREG',
                        'CCL3',
                        'CD83',
                        'CXCL2',
                        'CXCL3',
                        'IL1B',
                        'NAMPT',
                        'PLAUR',
                        'SRGN',
                        'THBS1',
                        'C1QA',
                        'C1QB',
                        'C1QC',
                        'CD163',
                        'CD5L',
                        'CTSB',
                        'FTL',
                        'HMOX1',
                        'MARCO',
                        'SEPP1',
                        'SLC40A1',
                        'VCAM1',
                        'ACP5',
                        'CSTB',
                        'FABP5',
                        'LGMN',
                        'PLD3',
                        'PSAP',
                        'APOE',
                        'CD14',
                        'CD54',
                        'CD68',
                        'FTH1',
                        'IL18',
                        'NINJ1',
                        'PLAC8',
                        'PLTP',
                        'VSIG4',
                        'CD74',
                        'HLA-DPA1',
                        'HLA-DQB1',
                        'HLA-DRA',
                        'HLA-DRB1',
                        'FCN1',
                        'LYZ',
                        'MNDA',
                        'S100A12',
                        'S100A4',
                        'S100A6',
                        'S100A8',
                        'S100A9',
                        'VCAN',
                        'CST3',
                        'BASP1',
                        'CSF3R',
                        'CXCL8',
                        'CXCR1',
                        'CXCR2',
                        'FCGR3B',
                        'FPR1',
                        'G0S2',
                        'IFITM2',
                        'S100A11',
                        'FCER1G',
                        'FOLR2',
                        'LYVE1',
                        'MS4A7',
                        'TIMD4',
                        'TIMP1',
                        'AIF1',
                        'COTL1',
                        'IFITM3',
                        'LST1'],
 'RBC': ['HBA1', 'HBA2', 'HBB', 'HBD'],
 'Stellate/Mesenchymal': ['CCL2',
                          'FBLN5',
                          'FOSB',
                          'JUNB',
                          'PDGFRA',
                          'SOCS3',
                          'SOD2',
                          'COLEC11',
                          'HGF',
                          'PTH1R',
                          'RBP1',
                          'RELN',
                          'VIPR1',
                          'ACTA2',
                          'COL1A1',
                          'COL1A2',
                          'MYL9',
                          'TAGLN',
                          'CD9',
                          'CRYAB',
                          'PMEPA1',
                          'RGCC'],
 'Tcell': ['GATA3',
           'FOXP3',
           'CTLA4',
           'IL2RA',
           'TIGIT',
           'TRGC2',
           'TRAC',
           'CD3E',
           'CD3D',
           'CMC1',
           'EOMES',
           'GZMK',
           'KLRB1',
           'IL7R',
           'SELL',
           'CCR7',
           'TPSAB1',
           'CPA3',
           'KIT',
           'GATA2',
           'TPSB2'],
 'Bcell': ['IGHD', 'IGHM'],
 'Dendritic': ['SCT',
               'CLEC4C',
               'LILRA4',
               'IL3RA',
               'TLR9',
               'TLR7',
               'CLEC10A',
               'XCR1',
               'BATF3',
               'CLEC9A',
               'LY75',
               'CD1C',
               'HLA-DPB1',
               'HLA-DQB1',
               'HLA-DPA1',
               'HLA-DRA'],
 'Macrophage': ['FCGR3B']}

SPECIFIC_CELLTYPE_MARKER_GENES = {'B cell': ['CD79A', 'CD79B'],
 'Naive B cell': ['IGHM'],
 'Plama B cell': ['IGHA1',
                  'IGHA2',
                  'IGHG1',
                  'IGHG2',
                  'IGHG3',
                  'IGHG4',
                  'IGHGP',
                  'IGKC',
                  'IGLC2',
                  'IGLC3',
                  'IGLL5'],
 'Cellcycle': ['BIRC5', 'CDC20', 'CDK1', 'CDK4', 'HMGB2', 'MKI67', 'TOP2A'],
 'ApoLipoChol': ['APOA1', 'APOA2', 'APOC1', 'APOC3'],
 'Cholangio': ['AGXT',
               'AMBP',
               'ANXA4',
               'CLDN1',
               'DEFB1',
               'EEF1A1',
               'EPCAM',
               'FXYD2',
               'GNB2L1',
               'HP',
               'MT2A',
               'NEAT1',
               'RPL3'],
 'KeratinsChol': ['KRT18', 'KRT19', 'KRT7', 'KRT8'],
 'Mucus Secreting': ['LGALS2',
                     'MUC1',
                     'MUC3A',
                     'MUC5B',
                     'PIGR',
                     'SCGB3A1',
                     'SLPI',
                     'SPINK1',
                     'TFF3'],
 'Arterial': ['CD34', 'PLVAP', 'PODXL'],
 'cvEndo': ['ACKR1', 'RSPO3', 'WNT2'],
 'cvLSEC': ['CLEC1B', 'CLEC4G', 'CLEC4M', 'CRHBP', 'FCN2', 'FCN3', 'STAB1', 'STAB2'],
 'Endothelial': ['C7',
                 'DNASE1L3',
                 'ENG',
                 'GSN',
                 'INMT',
                 'LIFR',
                 'PECAM1',
                 'PLAC8',
                 'RAMP3',
                 'TIMP3',
                 'VWF'],
 'ppLSEC': ['ADRIF', 'AQP1', 'CLEC14A', 'ID1', 'IGFBP7', 'MGP', 'S100A6', 'SPARCL1', 'TM4SF1'],
 'C-Hepato': ['ADH1A',
              'ADH1B',
              'ADH1C',
              'ADH4',
              'CES1',
              'CYP2E1',
              'CYP3A4',
              'CYP3A5',
              'DCXR',
              'GSTA1',
              'OAT'],
 'Hepatocyte': ['ASGR1', 'SERPINA1'],
 'P-Hepato': ['AGT',
              'ALB',
              'ALDOB',
              'APOA1',
              'CYP1A2',
              'CYP2A6',
              'CYP2A7',
              'CYP2D6',
              'FGA',
              'FGB',
              'GLS2',
              'HAL',
              'HAMP',
              'SDS'],
 'abT (incl. CD4+ & CD8+)': ['CD3D', 'CD3E', 'TRAC', 'TRBC2'],
 'CD4+ T': ['CD4', 'CD40LG', 'IL7R', 'LTB', 'RCAN3', 'S100A4', 'SPOCK2'],
 'CD8+ T': ['CD8A', 'CD8B'],
 'cNK': ['FCGR3A', 'GNLY', 'GZMB', 'TBX21', 'XCL2'],
 'gdT': ['CD7', 'CTSW', 'GATA3', 'TRDC', 'TRGC1', 'TRGC2'],
 'lrNK': ['CD69', 'CMC1', 'EOMES', 'GZMK', 'KLRC1', 'KLRF1', 'XCL1'],
 'ActivatedMac': ['AREG',
                  'CCL3',
                  'CD83',
                  'CXCL2',
                  'CXCL3',
                  'IL1B',
                  'NAMPT',
                  'PLAUR',
                  'SRGN',
                  'THBS1'],
 'Kupffer': ['C1QA',
             'C1QB',
             'C1QC',
             'CD163',
             'CD5L',
             'CTSB',
             'FTL',
             'HMOX1',
             'MARCO',
             'SEPP1',
             'SLC40A1',
             'VCAM1'],
 'LAM-like': ['ACP5', 'CSTB', 'FABP5', 'LGMN', 'PLD3', 'PSAP'],
 'Macrophage': ['APOE', 'CD14', 'CD54', 'CD68', 'FTH1', 'IL18', 'NINJ1', 'PLAC8', 'PLTP', 'VSIG4'],
 'MHCII/cDC': ['CD74', 'HLA-DPA1', 'HLA-DQB1', 'HLA-DRA', 'HLA-DRB1'],
 'Monocyte-derived': ['FCN1',
                      'LYZ',
                      'MNDA',
                      'S100A12',
                      'S100A4',
                      'S100A6',
                      'S100A8',
                      'S100A9',
                      'VCAN'],
 'Myeloid': ['CST3'],
 'Neutrophil': ['BASP1',
                'CSF3R',
                'CXCL8',
                'CXCR1',
                'CXCR2',
                'FCGR3B',
                'FPR1',
                'G0S2',
                'IFITM2',
                'S100A11'],
 'ResidentMac': ['FCER1G', 'FOLR2', 'LYVE1', 'MS4A7', 'TIMD4', 'TIMP1'],
 'SynapseMac': ['AIF1', 'COTL1', 'IFITM3', 'LST1'],
 'RBC': ['HBA1', 'HBA2', 'HBB', 'HBD'],
 'AP1+ Stellate': ['CCL2', 'FBLN5', 'FOSB', 'JUNB', 'PDGFRA', 'SOCS3', 'SOD2'],
 'Quiescent Stellate': ['COLEC11', 'HGF', 'PTH1R', 'RBP1', 'RELN', 'VIPR1'],
 'Stellate-Fiber': ['ACTA2', 'COL1A1', 'COL1A2', 'MYL9', 'TAGLN'],
 'VSMC': ['CD9', 'CRYAB', 'PMEPA1', 'RGCC'],
 'Treg': ['GATA3', 'FOXP3', 'CTLA4', 'IL2RA'],
 'Naive B': ['IGHD', 'IGHM'],
 'NKT': ['TIGIT', 'TRGC2', 'TRAC', 'CD3E', 'CD3D', 'CMC1', 'EOMES', 'GZMK', 'KLRB1'],
 'pDC': ['SCT', 'CLEC4C', 'LILRA4', 'IL3RA', 'TLR9', 'TLR7'],
 'cDC': ['CLEC10A', 'XCR1', 'BATF3', 'CLEC9A', 'LY75', 'CD1C'],
 'Dendritic': ['HLA-DPB1', 'HLA-DQB1', 'HLA-DPA1', 'HLA-DRA'],
 'Naive T cell': ['IL7R', 'SELL', 'CCR7'],
 'MAST cell': ['TPSAB1', 'CPA3', 'KIT', 'GATA2', 'TPSB2']}

# Double check to see if "feature_name" var contains gene symbols. It does
print(adata.var.columns.tolist())
display(adata.var.head())

for column in [
    "feature_id",
    "feature_name",
    "gene_id",
    "gene_ids",
    "gene_symbol",
    "gene_symbols",
    "symbol",
]:
    if column in adata.var.columns:
        print(
            column,
            "non-null:",
            adata.var[column].notna().sum(),
            "unique:",
            adata.var[column].nunique(dropna=True),
        )

# Use var.feature_name and set to var_names

# save ensemble id from adata.var
adata.var["ensembl_id"] = adata.var_names.astype(str)

# remove white space from gene symbols and store as pandas string type
gene_symbols = (
    adata.var["feature_name"].astype("string").str.strip()
)

# Empty strings will be missing valuyes
gene_symbol = gene_symbols.replace("",pd.NA)

# Fing genes with no gene symbol and keep ensemble id
missing_symbol_mask = gene_symbol.isna()

print(f"Total features: {adata.n_vars:,}")

print(
    f"Features with gene symbols: "
    f"{(~missing_symbol_mask).sum():,}"
)

print(
    f"Features without gene symbols: "
    f"{missing_symbol_mask.sum():,}"
)

# Create the final variable name labels
# use gene symbols where available
final_var_names = gene_symbols.fillna(adata.var["ensembl_id"])


# Save the final sybol or fallback label in adata.var
# This creates an explicit metadata column showing the exact label
# that will become the AnnData variable index.
adata.var["gene_symbol"] = gene_symbols
adata.var["gene_label"] = final_var_names

adata.var

# Define function to filter dataset for marker genes
def filter_marker_dict(marker_dict, adata):
    """
    Keep only marker genes that are present in adata.var_names.

    Parameters
    ----------
    marker_dict : dict
        Dictionary mapping cell type names to marker gene lists.
    adata : anndata.AnnData
        AnnData object containing gene names in adata.var_names.

    Returns
    -------
    dict
        Dictionary with the same keys, but only available genes retained.
        Cell types with zero available markers are removed.
    """
    var_names = set(adata.var_names)

    return {
        cell_type: [gene for gene in marker_genes if gene in var_names]
        for cell_type, marker_genes in marker_dict.items()
        if any(gene in var_names for gene in marker_genes)
    }

# Call function
available_celltype_markers = filter_marker_dict(CELLTYPE_MARKER_GENES, adata)

available_specific_celltype_markers = filter_marker_dict(
    SPECIFIC_CELLTYPE_MARKER_GENES,
    adata
)

adata

# Instpect available marker genes
for cell_type, genes in available_celltype_markers.items():
    print(f"{cell_type}: {len(genes)} markers")

# Define function to flatten avialble marker gene dict
def flatten_marker_dict(marker_dict):
    """
    Flatten a marker dictionary into a sorted unique gene list.

    Parameters
    ----------
    marker_dict : dict
        Dictionary mapping cell type names to marker gene lists.

    Returns
    -------
    list
        Sorted unique marker genes.
    """
    return sorted({
        gene
        for marker_genes in marker_dict.values()
        for gene in marker_genes
    })

# Define function to find available marker genes
def get_available_marker_genes(marker_dict, adata):
    """
    Return available and missing marker genes for an AnnData object.
    """
    requested_genes = flatten_marker_dict(marker_dict)
    adata_genes = set(adata.var_names)

    available_genes = [
        gene for gene in requested_genes
        if gene in adata_genes
    ]

    missing_genes = sorted(set(requested_genes) - adata_genes)

    return available_genes, missing_genes

# Call function
available_celltype_genes, missing_celltype_genes = get_available_marker_genes(
    CELLTYPE_MARKER_GENES,
    adata
)

available_specific_genes, missing_specific_genes = get_available_marker_genes(
    SPECIFIC_CELLTYPE_MARKER_GENES,
    adata
)

X_celltype = adata[:, available_celltype_genes].X
X_specific = adata[:, available_specific_genes].X

print("available_celltype_genes:", available_celltype_markers)
print("available_specific_genes:", available_specific_genes)

# Combine marker genes into a single matrix
combined_marker_genes = sorted(
    set(flatten_marker_dict(CELLTYPE_MARKER_GENES))
    | set(flatten_marker_dict(SPECIFIC_CELLTYPE_MARKER_GENES))
)

available_combined_genes = [
    gene for gene in combined_marker_genes
    if gene in set(adata.var_names)
]

# Define X
X = adata[:, available_combined_genes].X

# Check for sparse matrix and convert to dense array
if sparse.issparse(X):
  X = X.toarray()


expr = pd.DataFrame(X, columns = available_combined_genes)
expr["obs_id"] = adata.obs_names


# Define Expression log
expr_long = expr.melt(
    id_vars="obs_id",
    var_name="gene",
    value_name="expression"
)

# Save to parquet
expr_long.to_parquet(silver_path/ "marker_expression_long.parquet", index=False)

# Re-run filtering now that var_names are Symbols
available_celltype_markers = filter_marker_dict(CELLTYPE_MARKER_GENES, adata)
available_specific_celltype_markers = filter_marker_dict(SPECIFIC_CELLTYPE_MARKER_GENES, adata)

# Combine markers for the final export
combined_marker_genes = sorted(
    set(flatten_marker_dict(CELLTYPE_MARKER_GENES))
    | set(flatten_marker_dict(SPECIFIC_CELLTYPE_MARKER_GENES))
)

available_combined_genes = [g for g in combined_marker_genes if g in adata.var_names]

# Extract and melt data
X_sub = adata[:, available_combined_genes].X
if sparse.issparse(X_sub):
    X_sub = X_sub.toarray()

expr_final = pd.DataFrame(X_sub, columns=available_combined_genes)
expr_final["obs_id"] = adata.obs_names

expr_long_final = expr_final.melt(
    id_vars="obs_id",
    var_name="gene",
    value_name="expression"
)

# Save to parquet
expr_long_final.to_parquet(silver_path / "marker_expression_long.parquet", index=False)

print(f"Successfully exported {len(available_combined_genes)} marker genes to silver layer.")
print(f"Preview of markers found: {available_combined_genes[:10]}")

