# -*- coding: utf-8 -*-
"""download_cellxgene.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B59geCTCyj5aYTOiO1JoQa-r_3e0RTCx
"""

# Install packages
!pip install -q cellxgene-census scanpy anndata pyarrow pandas typing_extensions --upgrade

# Import packages
import cellxgene_census
import pandas as pd

# init CellxGene Census and check the top
census = cellxgene_census.open_soma()

datasets = (
    census["census_info"]["datasets"]
    .read()
    .concat()
    .to_pandas()
)

datasets.head()

# Basic keyword search over dataset and collection titles
query_terms = ["liver", "heart", "cardiac", "cardiomyocyte", "visium"]

mask = datasets["dataset_title"].str.contains("|".join(query_terms), case=False, na=False) | \
       datasets["collection_name"].str.contains("|".join(query_terms), case=False, na=False)

candidate_datasets = (
    datasets.loc[mask, [
        "collection_id",
        "collection_name",
        "dataset_id",
        "dataset_title",
        "dataset_total_cell_count"
    ]]
    .sort_values("dataset_total_cell_count")
)

candidate_datasets.head(25)

# Filter for Colab-scale candidates
colab_scale = candidate_datasets.query(
    "dataset_total_cell_count <= 50000"
).sort_values("dataset_total_cell_count")

colab_scale.head(20)

import os
from google.colab import drive

# Ensure the mount point directory is clear before attempting to mount.
# The 'ValueError: Mountpoint must not already contain files' indicates that
# /content/drive contains files even when force_remount is used.
# This often happens due to lingering artifacts from previous sessions or failed mounts.
if os.path.exists('/content/drive') and os.path.isdir('/content/drive'):
    print("Removing existing /content/drive directory to ensure a clean mount point.")
    # Use !rm -rf to forcefully remove the directory and its contents.
    # drive.mount() will recreate the directory if it doesn't exist.
    !rm -rf /content/drive

# Now attempt to mount Google Drive. force_remount=True handles cases
# where it might have been successfully mounted before (e.g., in a different cell).
print("Attempting to mount Google Drive.")
drive.mount("/content/drive", force_remount=True)

# Download Data
from pathlib import Path
import cellxgene_census

# Replace this after selecting from candidate_datasets
dataset_id = "a0805e92-3d1f-4866-af5c-5b903c6d910b"

drive_path = Path("/content/drive/MyDrive/Colab Notebooks/SpatialCell_Lakehouse/data/bronze")
drive_path.mkdir(parents=True, exist_ok=True)

out_file = drive_path / f"{dataset_id}.h5ad"

cellxgene_census.download_source_h5ad(
    dataset_id,
    to_path=str(out_file)
)

print(out_file)

import os

if os.path.exists(out_file):
    print(f"The file '{out_file}' exists in your Google Drive.")
else:
    print(f"The file '{out_file}' does NOT exist in your Google Drive.")

