"""Curated marker panels from published human liver differential-expression results.

The general marker dictionary represents broad cell-type or compartment
categories, while the specific dictionary represents more granular cell types
or states. In Visium data, marker expression indicates enrichment within spots;
it does not by itself establish a definitive cell identity. Visium observations
should therefore be described as spots rather than individual cells.
"""

MARKER_PANEL_METADATA: dict[str, object] = {
    "panel_name": "Curated human liver cell-type marker panel",
    "organism": "Homo sapiens",
    "tissue": "liver",
    "source_type": "Published human liver differential-expression results",
    "source_publication": (
        "Exact publication citation unavailable in the audited repository source "
        "(citation placeholder)"
    ),
    "source_table_or_worksheet": (
        "Audited Gene, Specific Type, and General Type columns; source table or "
        "worksheet name unavailable"
    ),
    "curation_method": (
        "Grouped Gene values by the audited General Type and Specific Type labels, "
        "preserved source ordering, and removed only exact within-group duplicates"
    ),
    "curator": "Not recorded in the audited repository source",
    "curation_date": "Not recorded in the audited repository source",
    "biological_interpretation_notes": (
        "Marker expression in Visium spots supports compartment, lineage, or "
        "cell-type enrichment interpretation but does not establish definitive "
        "identity for an individual cell."
    ),
}


CELLTYPE_MARKER_GENES: dict[str, tuple[str, ...]] = {
    "B cell": (
        "CD79A",
        "CD79B",
        "IGHM",
        "IGHA1",
        "IGHA2",
        "IGHG1",
        "IGHG2",
        "IGHG3",
        "IGHG4",
        "IGHGP",
        "IGKC",
        "IGLC2",
        "IGLC3",
        "IGLL5",
    ),
    "Cellcycle": ("BIRC5", "CDC20", "CDK1", "CDK4", "HMGB2", "MKI67", "TOP2A"),
    "Cholangiocyte": (
        "APOA1",
        "APOA2",
        "APOC1",
        "APOC3",
        "AGXT",
        "AMBP",
        "ANXA4",
        "CLDN1",
        "DEFB1",
        "EEF1A1",
        "EPCAM",
        "FXYD2",
        "GNB2L1",
        "HP",
        "MT2A",
        "NEAT1",
        "RPL3",
        "KRT18",
        "KRT19",
        "KRT7",
        "KRT8",
        "LGALS2",
        "MUC1",
        "MUC3A",
        "MUC5B",
        "PIGR",
        "SCGB3A1",
        "SLPI",
        "SPINK1",
        "TFF3",
    ),
    "Endothelial": (
        "CD34",
        "PLVAP",
        "PODXL",
        "ACKR1",
        "RSPO3",
        "WNT2",
        "CLEC1B",
        "CLEC4G",
        "CLEC4M",
        "CRHBP",
        "FCN2",
        "FCN3",
        "STAB1",
        "STAB2",
        "C7",
        "DNASE1L3",
        "ENG",
        "GSN",
        "INMT",
        "LIFR",
        "PECAM1",
        "PLAC8",
        "RAMP3",
        "TIMP3",
        "VWF",
        "ADRIF",
        "AQP1",
        "CLEC14A",
        "ID1",
        "IGFBP7",
        "MGP",
        "S100A6",
        "SPARCL1",
        "TM4SF1",
    ),
    "Hepatocyte": (
        "ADH1A",
        "ADH1B",
        "ADH1C",
        "ADH4",
        "CES1",
        "CYP2E1",
        "CYP3A4",
        "CYP3A5",
        "DCXR",
        "GSTA1",
        "OAT",
        "ASGR1",
        "SERPINA1",
        "AGT",
        "ALB",
        "ALDOB",
        "APOA1",
        "CYP1A2",
        "CYP2A6",
        "CYP2A7",
        "CYP2D6",
        "FGA",
        "FGB",
        "GLS2",
        "HAL",
        "HAMP",
        "SDS",
    ),
    "Lymphocyte": (
        "CD3D",
        "CD3E",
        "TRAC",
        "TRBC2",
        "CD4",
        "CD40LG",
        "IL7R",
        "LTB",
        "RCAN3",
        "S100A4",
        "SPOCK2",
        "CD8A",
        "CD8B",
        "FCGR3A",
        "GNLY",
        "GZMB",
        "TBX21",
        "XCL2",
        "CD7",
        "CTSW",
        "GATA3",
        "TRDC",
        "TRGC1",
        "TRGC2",
        "CD69",
        "CMC1",
        "EOMES",
        "GZMK",
        "KLRC1",
        "KLRF1",
        "XCL1",
    ),
    "Macrophage/Myeloid": (
        "AREG",
        "CCL3",
        "CD83",
        "CXCL2",
        "CXCL3",
        "IL1B",
        "NAMPT",
        "PLAUR",
        "SRGN",
        "THBS1",
        "C1QA",
        "C1QB",
        "C1QC",
        "CD163",
        "CD5L",
        "CTSB",
        "FTL",
        "HMOX1",
        "MARCO",
        "SEPP1",
        "SLC40A1",
        "VCAM1",
        "ACP5",
        "CSTB",
        "FABP5",
        "LGMN",
        "PLD3",
        "PSAP",
        "APOE",
        "CD14",
        "CD54",
        "CD68",
        "FTH1",
        "IL18",
        "NINJ1",
        "PLAC8",
        "PLTP",
        "VSIG4",
        "CD74",
        "HLA-DPA1",
        "HLA-DQB1",
        "HLA-DRA",
        "HLA-DRB1",
        "FCN1",
        "LYZ",
        "MNDA",
        "S100A12",
        "S100A4",
        "S100A6",
        "S100A8",
        "S100A9",
        "VCAN",
        "CST3",
        "BASP1",
        "CSF3R",
        "CXCL8",
        "CXCR1",
        "CXCR2",
        "FCGR3B",
        "FPR1",
        "G0S2",
        "IFITM2",
        "S100A11",
        "FCER1G",
        "FOLR2",
        "LYVE1",
        "MS4A7",
        "TIMD4",
        "TIMP1",
        "AIF1",
        "COTL1",
        "IFITM3",
        "LST1",
    ),
    "RBC": ("HBA1", "HBA2", "HBB", "HBD"),
    "Stellate/Mesenchymal": (
        "CCL2",
        "FBLN5",
        "FOSB",
        "JUNB",
        "PDGFRA",
        "SOCS3",
        "SOD2",
        "COLEC11",
        "HGF",
        "PTH1R",
        "RBP1",
        "RELN",
        "VIPR1",
        "ACTA2",
        "COL1A1",
        "COL1A2",
        "MYL9",
        "TAGLN",
        "CD9",
        "CRYAB",
        "PMEPA1",
        "RGCC",
    ),
    "Tcell": (
        "GATA3",
        "FOXP3",
        "CTLA4",
        "IL2RA",
        "TIGIT",
        "TRGC2",
        "TRAC",
        "CD3E",
        "CD3D",
        "CMC1",
        "EOMES",
        "GZMK",
        "KLRB1",
        "IL7R",
        "SELL",
        "CCR7",
        "TPSAB1",
        "CPA3",
        "KIT",
        "GATA2",
        "TPSB2",
    ),
    "Bcell": ("IGHD", "IGHM"),
    "Dendritic": (
        "SCT",
        "CLEC4C",
        "LILRA4",
        "IL3RA",
        "TLR9",
        "TLR7",
        "CLEC10A",
        "XCR1",
        "BATF3",
        "CLEC9A",
        "LY75",
        "CD1C",
        "HLA-DPB1",
        "HLA-DQB1",
        "HLA-DPA1",
        "HLA-DRA",
    ),
    "Macrophage": ("FCGR3B",),
}


SPECIFIC_CELLTYPE_MARKER_GENES: dict[str, tuple[str, ...]] = {
    "B cell": ("CD79A", "CD79B"),
    "Naive B cell": ("IGHM",),
    "Plama B cell": (
        "IGHA1",
        "IGHA2",
        "IGHG1",
        "IGHG2",
        "IGHG3",
        "IGHG4",
        "IGHGP",
        "IGKC",
        "IGLC2",
        "IGLC3",
        "IGLL5",
    ),
    "Cellcycle": ("BIRC5", "CDC20", "CDK1", "CDK4", "HMGB2", "MKI67", "TOP2A"),
    "ApoLipoChol": ("APOA1", "APOA2", "APOC1", "APOC3"),
    "Cholangio": (
        "AGXT",
        "AMBP",
        "ANXA4",
        "CLDN1",
        "DEFB1",
        "EEF1A1",
        "EPCAM",
        "FXYD2",
        "GNB2L1",
        "HP",
        "MT2A",
        "NEAT1",
        "RPL3",
    ),
    "KeratinsChol": ("KRT18", "KRT19", "KRT7", "KRT8"),
    "Mucus Secreting": (
        "LGALS2",
        "MUC1",
        "MUC3A",
        "MUC5B",
        "PIGR",
        "SCGB3A1",
        "SLPI",
        "SPINK1",
        "TFF3",
    ),
    "Arterial": ("CD34", "PLVAP", "PODXL"),
    "cvEndo": ("ACKR1", "RSPO3", "WNT2"),
    "cvLSEC": (
        "CLEC1B",
        "CLEC4G",
        "CLEC4M",
        "CRHBP",
        "FCN2",
        "FCN3",
        "STAB1",
        "STAB2",
    ),
    "Endothelial": (
        "C7",
        "DNASE1L3",
        "ENG",
        "GSN",
        "INMT",
        "LIFR",
        "PECAM1",
        "PLAC8",
        "RAMP3",
        "TIMP3",
        "VWF",
    ),
    "ppLSEC": (
        "ADRIF",
        "AQP1",
        "CLEC14A",
        "ID1",
        "IGFBP7",
        "MGP",
        "S100A6",
        "SPARCL1",
        "TM4SF1",
    ),
    "C-Hepato": (
        "ADH1A",
        "ADH1B",
        "ADH1C",
        "ADH4",
        "CES1",
        "CYP2E1",
        "CYP3A4",
        "CYP3A5",
        "DCXR",
        "GSTA1",
        "OAT",
    ),
    "Hepatocyte": ("ASGR1", "SERPINA1"),
    "P-Hepato": (
        "AGT",
        "ALB",
        "ALDOB",
        "APOA1",
        "CYP1A2",
        "CYP2A6",
        "CYP2A7",
        "CYP2D6",
        "FGA",
        "FGB",
        "GLS2",
        "HAL",
        "HAMP",
        "SDS",
    ),
    "abT (incl. CD4+ & CD8+)": ("CD3D", "CD3E", "TRAC", "TRBC2"),
    "CD4+ T": ("CD4", "CD40LG", "IL7R", "LTB", "RCAN3", "S100A4", "SPOCK2"),
    "CD8+ T": ("CD8A", "CD8B"),
    "cNK": ("FCGR3A", "GNLY", "GZMB", "TBX21", "XCL2"),
    "gdT": ("CD7", "CTSW", "GATA3", "TRDC", "TRGC1", "TRGC2"),
    "lrNK": ("CD69", "CMC1", "EOMES", "GZMK", "KLRC1", "KLRF1", "XCL1"),
    "ActivatedMac": (
        "AREG",
        "CCL3",
        "CD83",
        "CXCL2",
        "CXCL3",
        "IL1B",
        "NAMPT",
        "PLAUR",
        "SRGN",
        "THBS1",
    ),
    "Kupffer": (
        "C1QA",
        "C1QB",
        "C1QC",
        "CD163",
        "CD5L",
        "CTSB",
        "FTL",
        "HMOX1",
        "MARCO",
        "SEPP1",
        "SLC40A1",
        "VCAM1",
    ),
    "LAM-like": ("ACP5", "CSTB", "FABP5", "LGMN", "PLD3", "PSAP"),
    "Macrophage": (
        "APOE",
        "CD14",
        "CD54",
        "CD68",
        "FTH1",
        "IL18",
        "NINJ1",
        "PLAC8",
        "PLTP",
        "VSIG4",
    ),
    "MHCII/cDC": ("CD74", "HLA-DPA1", "HLA-DQB1", "HLA-DRA", "HLA-DRB1"),
    "Monocyte-derived": (
        "FCN1",
        "LYZ",
        "MNDA",
        "S100A12",
        "S100A4",
        "S100A6",
        "S100A8",
        "S100A9",
        "VCAN",
    ),
    "Myeloid": ("CST3",),
    "Neutrophil": (
        "BASP1",
        "CSF3R",
        "CXCL8",
        "CXCR1",
        "CXCR2",
        "FCGR3B",
        "FPR1",
        "G0S2",
        "IFITM2",
        "S100A11",
    ),
    "ResidentMac": ("FCER1G", "FOLR2", "LYVE1", "MS4A7", "TIMD4", "TIMP1"),
    "SynapseMac": ("AIF1", "COTL1", "IFITM3", "LST1"),
    "RBC": ("HBA1", "HBA2", "HBB", "HBD"),
    "AP1+ Stellate": ("CCL2", "FBLN5", "FOSB", "JUNB", "PDGFRA", "SOCS3", "SOD2"),
    "Quiescent Stellate": ("COLEC11", "HGF", "PTH1R", "RBP1", "RELN", "VIPR1"),
    "Stellate-Fiber": ("ACTA2", "COL1A1", "COL1A2", "MYL9", "TAGLN"),
    "VSMC": ("CD9", "CRYAB", "PMEPA1", "RGCC"),
    "Treg": ("GATA3", "FOXP3", "CTLA4", "IL2RA"),
    "Naive B": ("IGHD", "IGHM"),
    "NKT": (
        "TIGIT",
        "TRGC2",
        "TRAC",
        "CD3E",
        "CD3D",
        "CMC1",
        "EOMES",
        "GZMK",
        "KLRB1",
    ),
    "pDC": ("SCT", "CLEC4C", "LILRA4", "IL3RA", "TLR9", "TLR7"),
    "cDC": ("CLEC10A", "XCR1", "BATF3", "CLEC9A", "LY75", "CD1C"),
    "Dendritic": ("HLA-DPB1", "HLA-DQB1", "HLA-DPA1", "HLA-DRA"),
    "Naive T cell": ("IL7R", "SELL", "CCR7"),
    "MAST cell": ("TPSAB1", "CPA3", "KIT", "GATA2", "TPSB2"),
}


SPECIFIC_TO_GENERAL_TYPE: dict[str, str] = {
    "B cell": "B cell",
    "Naive B cell": "B cell",
    "Plama B cell": "B cell",
    "Cellcycle": "Cellcycle",
    "ApoLipoChol": "Cholangiocyte",
    "Cholangio": "Cholangiocyte",
    "KeratinsChol": "Cholangiocyte",
    "Mucus Secreting": "Cholangiocyte",
    "Arterial": "Endothelial",
    "cvEndo": "Endothelial",
    "cvLSEC": "Endothelial",
    "Endothelial": "Endothelial",
    "ppLSEC": "Endothelial",
    "C-Hepato": "Hepatocyte",
    "Hepatocyte": "Hepatocyte",
    "P-Hepato": "Hepatocyte",
    "abT (incl. CD4+ & CD8+)": "Lymphocyte",
    "CD4+ T": "Lymphocyte",
    "CD8+ T": "Lymphocyte",
    "cNK": "Lymphocyte",
    "gdT": "Lymphocyte",
    "lrNK": "Lymphocyte",
    "ActivatedMac": "Macrophage/Myeloid",
    "Kupffer": "Macrophage/Myeloid",
    "LAM-like": "Macrophage/Myeloid",
    "Macrophage": "Macrophage/Myeloid",
    "MHCII/cDC": "Macrophage/Myeloid",
    "Monocyte-derived": "Macrophage/Myeloid",
    "Myeloid": "Macrophage/Myeloid",
    "Neutrophil": "Macrophage/Myeloid",
    "ResidentMac": "Macrophage/Myeloid",
    "SynapseMac": "Macrophage/Myeloid",
    "RBC": "RBC",
    "AP1+ Stellate": "Stellate/Mesenchymal",
    "Quiescent Stellate": "Stellate/Mesenchymal",
    "Stellate-Fiber": "Stellate/Mesenchymal",
    "VSMC": "Stellate/Mesenchymal",
    "Treg": "Tcell",
    "Naive B": "Bcell",
    "NKT": "Tcell",
    "pDC": "Dendritic",
    "cDC": "Dendritic",
    "Dendritic": "Dendritic",
    "Naive T cell": "Tcell",
    "MAST cell": "Tcell",
}
